name: Mobile Security Scan - GitHub Actions

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'builds/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * *'  # Daily at 2 AM

jobs:
  mobscan:
    name: Run Mobile Security Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [
          { path: 'builds/app.apk', platform: 'android', name: 'Main App' },
          # Add more apps here
        ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Mobscan
        run: |
          pip install -e .

      - name: Verify app file exists
        run: |
          if [ ! -f "${{ matrix.app.path }}" ]; then
            echo "App file not found: ${{ matrix.app.path }}"
            exit 1
          fi

      - name: Run Mobscan
        run: |
          mobscan scan "${{ matrix.app.path }}" \
            --platform ${{ matrix.app.platform }} \
            --output-dir ./reports/${{ matrix.app.name }} \
            --format json,pdf,markdown \
            --intensity full \
            --masvs-level L1 L2 \
            --parallel 4 \
            --timeout 3600 \
            --verbose

      - name: Parse results
        if: always()
        run: |
          python scripts/parse_results.py \
            ./reports/${{ matrix.app.name }}/scan_result.json

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: security-reports-${{ matrix.app.name }}
          path: reports/${{ matrix.app.name }}/
          retention-days: 30

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('./reports/${{ matrix.app.name }}/scan_result.json'));

            const comment = `## 🔒 Mobile Security Scan Results

            **App**: ${{ matrix.app.name }}
            **Platform**: ${{ matrix.app.platform }}

            ### Risk Summary
            - Critical: ${report.risk_metrics.critical}
            - High: ${report.risk_metrics.high}
            - Medium: ${report.risk_metrics.medium}
            - Low: ${report.risk_metrics.low}
            - Risk Score: ${report.risk_metrics.risk_score}/10

            [View Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Fail on critical findings
        if: always()
        run: |
          CRITICAL=$(jq '.risk_metrics.critical' ./reports/${{ matrix.app.name }}/scan_result.json)
          HIGH=$(jq '.risk_metrics.high' ./reports/${{ matrix.app.name }}/scan_result.json)

          if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
            echo "Critical or High vulnerabilities found!"
            exit 1
          fi

      - name: Upload to security dashboard
        if: github.ref == 'refs/heads/main'
        env:
          DASHBOARD_URL: ${{ secrets.SECURITY_DASHBOARD_URL }}
          API_KEY: ${{ secrets.SECURITY_API_KEY }}
        run: |
          curl -X POST "$DASHBOARD_URL/api/v1/scans" \
            -H "Authorization: Bearer $API_KEY" \
            -H "Content-Type: application/json" \
            -d @./reports/${{ matrix.app.name }}/scan_result.json

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: |
          pytest tests/ --cov=mobscan --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml

  lint:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install black flake8 mypy

      - name: Format check
        run: black --check mobscan/

      - name: Lint
        run: flake8 mobscan/ --max-line-length=120

      - name: Type check
        run: mypy mobscan/ --ignore-missing-imports

  security-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install safety bandit

      - name: Security check
        run: safety check

      - name: Bandit scan
        run: bandit -r mobscan/ --skip B101

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: mobscan:latest
